services:
  app:
    container_name: tenants-frontend
    image: hcr.io/vjfloyd/${DOCKER_IMAGE}:${IMAGE_TAG:-latest}
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - TENANTS_API=${TENANTS_API}
networks:
  tenants-network:
    name: tenants-network
    external: true
