services:
  tenants-frontend:
    image: ghcr.io/${IMAGE_NAME}:${IMAGE_TAG:-latest}
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    environment:
      - TENANTS_API
      - NEXT_PUBLIC_TENANTS_API
      - NEXT_PUBLIC_BUILD_ID
    networks:
      - tenants-network
networks:
  tenants-network:
    name: tenants-network
    external: true
